# Generated by Django 6.0.5 on 2026-05-21 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Team Name')),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name', models.CharField(blank=True, max_length=10, null=True)),
                ('cap_name', models.CharField(max_length=50, verbose_name='Captain Name')),
                ('cap_surname', models.CharField(max_length=50, verbose_name='Captain Surname')),
                ('cap_email', models.EmailField(max_length=100, unique=True)),
                ('cap_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('payment_status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Accepted'), (2, 'Refund')], default=0)),
                ('blik_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Assigned BLIK')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid'), ('APPROVED', 'Approved')], default='REGISTERED', max_length=20, verbose_name='Registration Status')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Checked In')),
                ('roster_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Roster Access Code')),
                ('entrance_source', models.CharField(blank=True, default='soundcloud', max_length=20, null=True)),
                ('entrance_url', models.URLField(blank=True, max_length=500, null=True)),
                ('entrance_title', models.CharField(blank=True, max_length=200, null=True)),
                ('entrance_artist', models.CharField(blank=True, max_length=200, null=True)),
                ('entrance_artwork_url', models.URLField(blank=True, max_length=500, null=True)),
                ('entrance_start_seconds', models.PositiveIntegerField(default=0)),
                ('entrance_duration_seconds', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('team', 'Team'), ('checkin', 'Check-in')], db_index=True, max_length=20)),
                ('action', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True, default='')),
                ('entity_type', models.CharField(blank=True, default='', max_length=40)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('entity_label', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('jersey_number', models.CharField(blank=True, default='', max_length=3)),
                ('position', models.CharField(blank=True, choices=[('OH', 'Outside Hitter'), ('MB', 'Middle Blocker'), ('S', 'Setter'), ('OPP', 'Opposite'), ('L', 'Libero')], default='', max_length=3)),
                ('photo_path', models.CharField(blank=True, default='', max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.team')),
            ],
            options={
                'db_table': 'Players',
            },
        ),
        migrations.CreateModel(
            name='TeamFanVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='One confirmed vote per email address.', max_length=254, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_votes', to='tournament.team')),
            ],
            options={
                'db_table': 'team_fan_votes',
            },
        ),
    ]
